import UWP

public protocol IBufferProtocol: WindowsStorageStreams_IBufferProtocol {}
public typealias IBuffer = WindowsStorageStreams_IBuffer
public typealias IBufferProjection = WindowsStorageStreams_IBufferProjection