#include <wtypesbase.h>
#include <minwindef.h>
#include <winnt.h>
#include <combaseapi.h>
#include <Winerror.h>
#include <roapi.h>
#include <robuffer.h>
#include <winstring.h>
#include <windows.foundation.collections.h>
#include <windows.security.cryptography.core.h>
