import UWP_Assembly

public typealias CryptographicHash = WindowsSecurityCryptographyCore_CryptographicHash
public typealias HashAlgorithmProvider = WindowsSecurityCryptographyCore_HashAlgorithmProvider